books/urls.py
from django.urls import path

from . import views

app_name = 'books'
urlpatterns = [
    path('', views.BookListView.as_view(), name='index'), 
    path('search/', views.search_books, name='search'),
    path('create/', views.create_book, name='create'),
    path('<int:book_id>/', views.detail_book, name='detail'), 
    path("update/<int:book_id>/", views.update_book, name="update"),
    path("delete/<int:book_id>/", views.delete_book, name="delete"),
    path('<int:pk>/review/', views.create_review, name='review'),
    path('lists/', views.ListListView.as_view(), name='lists'),
    path('lists/create', views.ListCreateView.as_view(), name='create-list'),
    path('categorias/', views.categorias, name='categorias'),
    path('categorias/<str:categoria>/', views.posts_por_categoria, name='posts_por_categoria')
]

booksite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('staticpages.urls')),
    path('books/', include('books.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock %} | Leitura Geral
    </title>
    <link href="https://fonts.googleapis.com/css?family=Inter&display=swap" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>

<body>
    <header id="cabecalho-principal">
        <a href="{% url 'index' %}"> <img src="{% static 'final.svg' %}"> </a>
        <nav id="navegacao-principal">
            <ul>
                {% if user.is_authenticated %}
                    <li> Logado com {{ user.username }} </li>
                    <li><a href="{% url 'logout' %}">Log out</a></li>
                {% else %}
                    <li><a href="{% url 'login' %}">Log in</a></li>
                {% endif %}
                {% if not user.is_authenticated %}
                <li><a href="{% url 'signup' %}">Signup</a></li>
                {% endif %}
                <li><a href="{% url 'books:index' %}">Livros</a></li>
                <li><a href="{% url 'books:lists' %}">Listas</a></li>
                <li><a href="{% url 'about' %}">Sobre</a></li>
            </ul>
        </nav>

    </header>
    <main id="conteiner-principal">
        {% block content %}
        {% endblock content %}
    </main>
    <footer>
        <p>&copy; 2023 BlogShelved. Todos os direitos reservados.</p>
    </footer>
</body>

</html>