books/urls.py
from django.urls import path

from . import views

app_name = 'books'
urlpatterns = [
    path('', views.BookListView.as_view(), name='index'), 
    path('search/', views.search_books, name='search'),
    path('create/', views.create_book, name='create'),
    path('<int:book_id>/', views.detail_book, name='detail'), 
    path("update/<int:book_id>/", views.update_book, name="update"),
    path("delete/<int:book_id>/", views.delete_book, name="delete"),
    path('<int:pk>/review/', views.create_review, name='review'),
    path('lists/', views.ListListView.as_view(), name='lists'),
    path('lists/create', views.ListCreateView.as_view(), name='create-list'),
    path('categorias/', views.categorias, name='categorias'),
    path('categorias/<str:categoria>/', views.posts_por_categoria, name='posts_por_categoria')
]

booksite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('staticpages.urls')),
    path('books/', include('books.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

books/models.py
from django.db import models

# Create your models here.


from django.db import models
from django.conf import settings
from datetime import datetime


class Book(models.Model):
    name = models.CharField(max_length=255)
    release_year = models.IntegerField()
    capa_url = models.URLField(max_length=200, null=True)
    categoria = models.CharField(max_length=255 , null = True)
    data = models.DateField(auto_now_add=True)

    def __str__(self):
        return f'{self.name}({self.categoria})({self.release_year})'

class Review(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    text = models.CharField(max_length=255)
    likes = models.IntegerField(default=0)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    data = models.DateField(auto_now_add=True)

    def __str__(self):
        return f'"{self.text}" - {self.author.username}'

class List(models.Model):
    author = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    books = models.ManyToManyField(Book)

    def __str__(self):
        return f'{self.name} by {self.author}'

books/forms.py
from django.forms import ModelForm
from .models import Book, Review


class BookForm(ModelForm):
    class Meta:
        model = Book
        fields = [
            'name',
            'release_year',
            'capa_url',
            'categoria',
        ]
        labels = {
            "name": "Título",
            "categoria": "Ano de publicação",
            "capa_url": "URL da Imagem",
            "categoria": "Categoria de Livro"
        }


class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = [
            'text',
        ]
        labels = {
            'text': 'Critica',
        }



books/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse
from .temp_data import book_data
from django.shortcuts import render
from .models import Book
from django.shortcuts import render, get_object_or_404
from django.views import generic
from .forms import BookForm
from .models import Book, Review
from .forms import BookForm, ReviewForm
from django.urls import reverse, reverse_lazy
from .models import Book, Review, List
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

class BookListView(generic.ListView):
    model = Book
    template_name = 'books/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if 'last_viewed' in self.request.session:
            context['last_books'] = []
            for book_id in self.request.session['last_viewed']:
                context['last_books'].append(
                    get_object_or_404(Book, pk=book_id))
        return context



#class BookDetailView(generic.DetailView):
#    model = Book
#    template_name = 'books/detail.html'

class BookListView(generic.ListView):
    model = Book
    template_name = 'books/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if 'last_viewed' in self.request.session:
            context['last_books'] = []
            for book_id in self.request.session['last_viewed']:
                context['last_books'].append(
                    get_object_or_404(Book, pk=book_id))
        return context


@login_required
@permission_required('books.delete_book')
def delete_book(request, book_id):
    book = get_object_or_404(Book, pk=book_id)

    if request.method == "POST":
        book.delete()
        return HttpResponseRedirect(reverse("books:index"))

    context = {"book": book}
    return render(request, "books/delete.html", context)



def search_books(request):
    context = {}
    if request.GET.get("query", False):
        search_term = request.GET["query"].lower()
        book_list = Book.objects.filter(name__icontains=search_term)
        context = {"book_list": book_list}
    return render(request, "books/search.html", context)


@login_required
@permission_required('books.add_book')
def create_book(request):
    if request.method == 'POST':
        form =BookForm(request.POST)
        if form.is_valid():
            book_name = form.cleaned_data['name']
            book_release_year = form.cleaned_data['release_year']
            book_capa_url = form.cleaned_data['capa_url']
            book_categoria = form.cleaned_data['categoria']
            book = Book(name=book_name,
                          release_year=book_release_year,
                          capa_url=book_capa_url,
                          categoria=book_categoria)
            book.save()
            return HttpResponseRedirect(
                reverse('books:detail', args=(book.id, )))
    else:
        form = BookForm()
    context = {'form': form}
    return render(request, 'books/create.html', context)

    
@login_required
def create_review(request, pk):
    book = get_object_or_404(Book, pk=pk)
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review_author = request.user
            review_text = form.cleaned_data['text']
            comentario = Review(author=review_author, text=review_text, book=book)
            comentario.save()
            return HttpResponseRedirect(
                reverse('books:detail', args=(pk, )))
    else:
        form = ReviewForm()
    context = {'form': form, 'book': book}
    return render(request, 'books/review.html', context)

@login_required
@permission_required('books.update_book')
def update_book(request, book_id):
    book = get_object_or_404(Book, pk=book_id)

    if request.method == "POST":
        form = BookForm(request.POST)
        if form.is_valid():
            book.name = form.cleaned_data["name"]
            book.release_year = form.cleaned_data["release_year"]
            book.poster_url = form.cleaned_data["capa_url"]
            book.categoria = form.cleaned_data['categoria']
            book.save()
            return HttpResponseRedirect(reverse("books:detail", args=(book.id,)))
    else:
        form = BookForm(
            initial={
                "name": book.name,
                "release_year": book.release_year,
                "capa_url": book.capa_url,
                'categoria': book.categoria,
            }
        )

    context = {"book": book, "form": form}
    return render(request, "books/update.html", context)



def detail_book(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    if 'last_viewed' not in request.session:
        request.session['last_viewed'] = []
    request.session['last_viewed'] = [book_id
                                      ] + request.session['last_viewed']
    if len(request.session['last_viewed']) > 5:
        request.session['last_viewed'] = request.session['last_viewed'][:-1]
    context = {'book': book}
    return render(request, 'books/detail.html', context)

def categorias(request):
    categorias = Book.objects.values_list('categoria', flat=True).distinct()
    categorias_e_livros = {}
    
    for categoria in categorias:
        books = Book.objects.filter(categoria=categoria)
        categorias_e_livros[categoria] = books

    return render(request, 'books/categorias.html', {'categorias_e_livros': categorias_e_livros})

def posts_por_categoria(request, categoria):
    books = Book.objects.filter(categoria=categoria)
    return render(request, 'books/posts_por_categoria.html', {'books':books, 'categoria': categoria})


class ListListView(generic.ListView):
    model = List
    template_name = 'books/lists.html'


class ListCreateView(LoginRequiredMixin, PermissionRequiredMixin,
                     generic.CreateView):
    model = List
    template_name = 'books/create_list.html'
    fields = ['name', 'author', 'books']
    success_url = reverse_lazy('books:lists')
    permission_required = 'books.add_list'

    def get_form(self, *args, **kwargs):
        form = super().get_form(*args, **kwargs)
        # Exclude the 'author' field from the form
        form.fields.pop('author', None)
        return form

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

books/templates/books/categorias.html
{% extends 'base.html' %}

{% block content %}
    <h2>Todas as Categorias</h2>
    <ul>
        {% for categoria, books in categorias_e_livros.items %}
            <li><a href="{% url 'books:posts_por_categoria' categoria=categoria %}">
                <u style="text-decoration: underline;">{{ categoria }}</u>
            </a></li>
            <ul>
                {% for book in books %}
                    <li>
                        <div style="margin-bottom: 10px;">
                            <strong>{{ book.name }}</strong>
                        </div>
                        <a href="{% url 'books:detail' book.id %}">
                            <img src="{{ book.image_url }}" alt="{{ book.name }}" style="max-width: 200px; height: auto; display: block;">
                        </a>
                    </li>
                {% endfor %}
            </ul>
        {% endfor %}
    </ul>
{% endblock %}

books/templates/books/create.html
{% extends 'base.html' %}

{% block content %}
<h2>Inserir Novo Livro</h2>
<form method="post" action="{% url 'books:create' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Criar</button>
</form>

{% endblock content %}

books/templates/books/create_list.html
{% extends 'base.html' %}
{% block title %}
    Criar Livro
{% endblock title %}
{% block content %}
    <h2>Criar Lista</h2>
    <form action="{% url 'books:create-list' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Criar</button>
    </form>
{% endblock content %}

books/templates/books/delete.html
{% extends 'base.html' %}
{% block content %}
    <form action="{% url 'books:delete' book.id %}" method="post">
        {% csrf_token %}
        <p>Você tem certeza que deseja apagar o livro? "{{ book.name }} ({{ book.release_year }})"?</p>
        <button type="submit">Apagar</button>
    </form>
{% endblock content %}

books/templates/books/detail.html
{% extends 'base.html' %}
{% block title %}
    {{ book.name }} (<a href="{% url 'books:posts_por_categoria' categoria=book.categoria %}">{{ book.categoria }}</a>)
{% endblock title %}

{% block content %}
    <h2>{{ book.name }}</h2>
    <section class="dados-de-livro">
        <img src="{{ book.capa_url }}" alt="Capa do Livro {{ book.name }}">
        <ul>
            <li><u>Nome</u>: <strong>{{ book.name }}</strong></li>
            <li><u>Categoria</u>: <strong><a href="{% url 'books:posts_por_categoria' categoria=book.categoria %}">{{ book.categoria }}</a></strong></li>
            <li><u>Ano de publicação</u>: <strong>{{book.release_year}}</strong></li>

            
            {% if book.list_set.all %}<li><u>Incluso nas listas</u>: {{ book.list_set.all|join:", " }}</li>{% endif %}
            <li>
                <a href="{% url 'books:update' book.id %}">Editar</a>
            </li>
            <li>
                <a href="{% url 'books:delete' book.id %}">Apagar</a>
            </li>
        </ul>
    </section>
<hr>

<section>
    <header>
        <h3>Críticas</h3>
    </header>
    <ul>
        {% if book.review_set.all %}
            {% for review in book.review_set.all|dictsortreversed:"id" %}
                <figure>
                    <blockquote>
                        "{{ review.text }}"
                    </blockquote>
                    <figcaption>—{{ review.author }}, {{review.data}}</figcaption>
                </figure>
            {% endfor %}
        {% else %}
            <p>Ainda não existe nenhuma crítica para esse livro.</p>
        {% endif %}
    </ul>

    <a href="{% url 'books:review' book.pk %}">
        <button>Crie sua Critica</button>
    </a>

</section>

{% endblock content %}

books/templates/books/index.html
{% extends 'base.html' %}

{% block content %}

<h2>Todos os Livros</h2>
<section>
    <p>Muitos resultados? <a href="{% url 'books:search' %}">Buscar Livros</a></p>


    {% if perms.books.add_book %}
    <p>Não encontrou o livro? <a href="{% url 'books:create' %}">Adicionar Novo Livro</a></p>
{% endif%}
</section>
{% if book_list %}

<section class="lista-de-cards">
    {% for book in book_list %}
    <article class="card">
        <a href="{% url 'books:detail' book.id %}"> 
            <img src="{{ book.capa_url }}" alt="Capa do livro {{ book.name}}">
        </a> 
        <p>{{ book.name }} ({{ book.release_year }}) ({{book.categoria}})</p>
    </article>
    {% endfor %}
</section>

{% else %}
<p>Não foi encontrado nenhum livro.</p>
{% endif %}


{% if last_book %}
<hr>
<h2>Último visto</h2>
<section class="lista-de-cards">
    <article class="small-card">
        <a href="{% url 'books:detail' last_book.id %}"><img src="{{ last_book.capa_url }}"
                alt="Capa do Livro {{ last_book.name}}"></a>
    </article>
</section>
{% endif %}

{% endblock content %}



books/templates/books/lists.html
{% extends 'base.html' %}
{% block title %}
    Listas
{% endblock title %}


{% block content %}
    <h2>Listas de Livros</h2>



    <section>
        {% for list in list_list %}
            <hr>
            <article>
                <header>
                    <h3>{{ list.name }} (de {{ list.author }})</h3>
                </header>
                <div class="lista-de-cards">
                    {% for book in list.books.all %}
                        <div class="card">
                            <a href="{% url 'books:detail' book.id %}"><img src="{{ book.capa_url }}" 
                                alt="Capa do livro {{ book.name }}">
                            </a>
                            <p>{{ book.name }} ({{ book.categoria }})</p>
                        </div>
                    {% endfor %}
                </div>
            </article>
        {% endfor %}

        <a href="{% url 'books:create-list' %}"><button>Crie sua Lista</button></a>
    </section>


{% endblock content %}

books/templates/books/posts_por_categoria.html
{% extends 'base.html' %}

{% block content %}
    <h2>Artigos da Categoria: {{ categoria }}</h2>
    <ul>
        {% for book in books %}
            <li>
                <div style="margin-bottom: 20px;">
                    <strong>{{ book.name }}</strong>
                </div>
                <div>
                    <a href="{% url 'books:detail' book.id %}">
                        <img src="{{ book.capa_url }}" alt="{{ book.name }}" style="max-width: 200px; height: auto; display: block;">
                    </a>
                </div>
            </li>
        {% empty %}
            <p>Nenhum livro foi encontrado para esta categoria.</p>
        {% endfor %}
    </ul>
{% endblock %}

books/templates/books/review.html
{% extends 'base.html' %}
{% block content %}
    <h2>Criticar Livro {{ book.name }} ({{ book.categoria }})</h2>
    <form action="{% url 'books:review' book.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Postar Critica</button>
    </form>
    <p>
        <a href="{% url 'books:detail' book.id %}">Voltar para a página do livro</a>
    </p>
{% endblock content %}

books/templates/books/search.html
{% extends 'base.html' %}

{% block content %}
<h2>Busca de Livros por Nome</h2>
<form action="{% url 'books:search' %}">
    <p>
        <label for="id_query">Título:</label>
        <input type="text" name="query" id="id_query" />
    </p>
    <button type="submit">Buscar</button>
</form>


<h2>Resultado da Busca</h2>
{% if book_list %}
<section class="lista-de-cards">
    {% for book in book_list %}
    <article class="card">
        <img src="{{ book.capa_url }}" alt="Capa do livro {{ book.name}}">
        <p>{{ book.name }} ({{ book.release_year }})</p>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Nenhum livro encontrado com a busca.</p>
{% endif %}

{% endblock content %}

books/templates/books/update.html
{% extends 'base.html' %}
{% block content %}
    <h2>Atualizar Dados do Livro {{ book.name }} ({{ book.release_year }})</h2>
    <form method="POST" action="{% url 'books:update' book.id %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Atualizar</button>
    </form>
{% endblock content %}
